spring:
  datasource:
    url: "jdbc:tc:postgresql:14.5:///${POSTGRES_DB:application_database}"
    username: ${POSTGRES_USER:application_api_username}
    password: ${POSTGRES_PASSWORD:application_api_password}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false